FROM node:16-alpine
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /data/

COPY ./package.json /data/

RUN yarn install --force --network-timeout 1000000

COPY . /data/

CMD yarn start